version: '3.4'

services:
  masterofcoin.api:
    image: ${DOCKER_REGISTRY-}masterofcoinapi
    build:
      context: ../
      dockerfile: MasterOfCoin.Service/MasterOfCoin.API/Dockerfile
    environment:
      ENV_NAME: local
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 80
      ConnectionStrings__TracingUri: "http://jaeger:14268/api/traces"
    ports:
      - "1234:80"
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "26687:16686"